services:
    elasticsearch:
        image: elasticsearch:8.17.4
        container_name: es
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: '-Xms512m -Xmx512m'
        ports:
            - '9200:9200'
            - '9300:9300'
        healthcheck:
            test: ['CMD-SHELL', 'curl --silent --fail localhost:9200/_cluster/health || exit 1']
            interval: 10s
            timeout: 10s
            retries: 3
        networks:
            - local_nw
    logstash:
        image: logstash:8.17.4
        container_name: log
        environment:
            discovery.seed_hosts: logstash
            LS_JAVA_OPTS: '-Xms512m -Xmx512m'
        volumes:
            - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
            - ./logstash/nginx.log:/home/nginx.log
        ports:
            - '8888:5000/tcp'
            - '8888:5000/udp'
            - '8044:5044'
            - '9600:9600'
        depends_on:
            - elasticsearch
        networks:
            - local_nw
        command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config
    kibana:
        image: kibana:8.17.4
        container_name: kib
        ports:
            - '8601:5601'
        depends_on:
            - elasticsearch
        networks:
            - local_nw
networks:
    local_nw:
        external: true
