services:
    nginx:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./html:/usr/share/nginx/html
            - ./logs:/var/log/nginx
        networks:
            - nginx_network

networks:
    nginx_network:
        driver: bridge
