services:
    redis:
        image: redis:latest
        container_name: redis-server
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        environment:
            - REDIS_PASSWORD=password@123

    redis-server:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        depends_on:
            - redis
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8081:8081'
        networks:
            - local_nw

volumes:
    redis-data:
        driver: local

networks:
    local_nw:
        external: true
