services:
    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password@123
        volumes:
            - mongo-data:/data/db
        networks:
            - local_nw

volumes:
    mongo-data:
        driver: local

networks:
    local_nw:
        external: true
