services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password123
        volumes:
            - mongo-data:/data/db
        networks:
            - local_nw
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        depends_on:
            mongo:
                condition: service_healthy
        ports:
            - '8081:8081'
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://root:password123@mongo:27017/
            ME_CONFIG_BASICAUTH_ENABLED: true
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: password123
        networks:
            - local_nw

volumes:
    mongo-data:

networks:
    local_nw:
        external: true
