services:
    mysql:
        image: mysql:latest
        container_name: mysql_container
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password@123
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - local_nw

volumes:
    mysql_data:
        driver: local

networks:
    local_nw:
        external: true
