services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password@123
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - pg_network

volumes:
    postgres_data:
        driver: local

networks:
    pg_network:
        driver: bridge
