services:
    postgres:
        image: postgres:17
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password@123
            POSTGRES_DB: root
            PGDATA: /var/lib/postgresql/data/pgdata
            TZ: 'Asia/Kolkata'
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - local_nw

volumes:
    postgres_data:

networks:
    local_nw:
        external: true
