services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2025-latest
        container_name: sqlserver
        restart: always
        environment:
            - SA_PASSWORD=password@123
            - ACCEPT_EULA=Y
        ports:
            - 1433:1433
        volumes:
            - sqlserver-data:/var/opt/mssql
        networks:
            - local_nw

volumes:
    sqlserver-data:
        driver: local

networks:
    local_nw:
        external: true
