services:
    wordpress:
        image: wordpress:latest
        ports:
            - '80:80'
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpressuser
            WORDPRESS_DB_PASSWORD: wordpresspassword
            WORDPRESS_DB_NAME: wordpressdb
        volumes:
            - ./wp-content:/var/www/html/wp-content # Persist wp-content
            - wpfiles:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: wordpressdb
            MYSQL_USER: wordpressuser
            MYSQL_PASSWORD: wordpresspassword
        volumes:
            - ./db_data:/var/lib/mysql # Persist database data
